### ISSUE TITLE
Incorporate the storage system for todo data

### ISSUE THREAD

**Issue by Thorbjorn2021** [Thorbjorn2021/TodoList#16]
- [x] Add button to save data
- [x] Add logic to button
- [x] Load data upon start of application
